/**
 * Migrations bundle for `@xangarro/data`.
 *
 * ⚠️  AUTO-GENERATED by `scripts/gen-migration-barrel.ts`.
 * Do not edit manually. Run `pnpm db:generate` to regenerate.
 *
 * 3 migration(s) registered.
 */

import journal from './meta/_journal.json';
import { migration0000Sql } from './0000_initial.js';
import { migration0001Sql } from './0001_add_business_fiscal.js';
import { migration0002Sql } from './0002_add_business_regimen_sat.js';

export const migrationSqlByTag: Readonly<Record<string, string>> = Object.freeze({
  '0000_initial': migration0000Sql,
  '0001_add_business_fiscal': migration0001Sql,
  '0002_add_business_regimen_sat': migration0002Sql,
});

export const migrationsBundle = Object.freeze({
  journal,
  migrations: Object.freeze({
    m0000: migration0000Sql,
    m0001: migration0001Sql,
    m0002: migration0002Sql,
  }),
});

export { journal, migration0000Sql, migration0001Sql, migration0002Sql };
export default migrationsBundle;
