/**
 * Migrations bundle for `@xangarro/data`.
 *
 * ⚠️  AUTO-GENERATED by `scripts/gen-migration-barrel.ts`.
 * Do not edit manually. Run `pnpm db:generate` to regenerate.
 *
 * 5 migration(s) registered.
 */

import journal from './meta/_journal.json';
import { migration0000Sql } from './0000_initial.js';
import { migration0001Sql } from './0001_capture_client.js';
import { migration0002Sql } from './0002_operator_only.js';
import { migration0003Sql } from './0003_stock_baseline.js';
import { migration0004Sql } from './0004_xangarro_sync_tables.js';

export const migrationSqlByTag: Readonly<Record<string, string>> = Object.freeze({
  '0000_initial': migration0000Sql,
  '0001_capture_client': migration0001Sql,
  '0002_operator_only': migration0002Sql,
  '0003_stock_baseline': migration0003Sql,
  '0004_xangarro_sync_tables': migration0004Sql,
});

export const migrationsBundle = Object.freeze({
  journal,
  migrations: Object.freeze({
    m0000: migration0000Sql,
    m0001: migration0001Sql,
    m0002: migration0002Sql,
    m0003: migration0003Sql,
    m0004: migration0004Sql,
  }),
});

export {
  journal,
  migration0000Sql,
  migration0001Sql,
  migration0002Sql,
  migration0003Sql,
  migration0004Sql,
};
export default migrationsBundle;
