/**
 * Migrations bundle for `@xangarro/data`.
 *
 * ⚠️  AUTO-GENERATED by `scripts/gen-migration-barrel.ts`.
 * Do not edit manually. Run `pnpm db:generate` to regenerate.
 *
 * 10 migration(s) registered. 0006–0009 arrived with the
 * rename/xangarro-stored-ids merge, renumbered onto main's journal
 * (main's 0000–0005 are untouched; the branch's in-place 0000 edits were
 * comment-only and are dropped).
 */

import journal from './meta/_journal.json';
import { migration0000Sql } from './0000_initial.js';
import { migration0001Sql } from './0001_add_business_fiscal.js';
import { migration0002Sql } from './0002_add_business_regimen_sat.js';
import { migration0003Sql } from './0003_mensajes_respuestas_operador.js';
import { migration0004Sql } from './0004_c18_receivables_expected_cash.js';
import { migration0005Sql } from './0005_c17_tickets_sales_lines.js';
import { migration0006Sql } from './0006_capture_client.js';
import { migration0007Sql } from './0007_operator_only.js';
import { migration0008Sql } from './0008_stock_baseline.js';
import { migration0009Sql } from './0009_xangarro_sync_tables.js';
import { migration0010Sql } from './0010_expenses_empleado.js';

export const migrationSqlByTag: Readonly<Record<string, string>> = Object.freeze({
  '0000_initial': migration0000Sql,
  '0001_add_business_fiscal': migration0001Sql,
  '0002_add_business_regimen_sat': migration0002Sql,
  '0003_mensajes_respuestas_operador': migration0003Sql,
  '0004_c18_receivables_expected_cash': migration0004Sql,
  '0005_c17_tickets_sales_lines': migration0005Sql,
  '0006_capture_client': migration0006Sql,
  '0007_operator_only': migration0007Sql,
  '0008_stock_baseline': migration0008Sql,
  '0009_xangarro_sync_tables': migration0009Sql,
  '0010_expenses_empleado': migration0010Sql,
});

export const migrationsBundle = Object.freeze({
  journal,
  migrations: Object.freeze({
    m0000: migration0000Sql,
    m0001: migration0001Sql,
    m0002: migration0002Sql,
    m0003: migration0003Sql,
    m0004: migration0004Sql,
    m0005: migration0005Sql,
    m0006: migration0006Sql,
    m0007: migration0007Sql,
    m0008: migration0008Sql,
    m0009: migration0009Sql,
    m0010: migration0010Sql,
  }),
});

export {
  journal,
  migration0000Sql,
  migration0001Sql,
  migration0002Sql,
  migration0003Sql,
  migration0004Sql,
  migration0005Sql,
  migration0006Sql,
  migration0007Sql,
  migration0008Sql,
  migration0009Sql,
};
export default migrationsBundle;
