#!/usr/bin/env tsx
/**
 * gen-migration-barrel.ts
 *
 * Auto-generates `drizzle/migrations/index.ts` from `_journal.json` and
 * the migration `.ts` files on disk. Run after creating or removing a
 * migration via `drizzle-kit generate` or `pnpm db:new`.
 *
 * This replaces the error-prone manual 4-step registration process:
 *   1. Create migration file ← still manual (or drizzle-kit generate)
 *   2. Edit index.ts imports  ← automated by this script
 *   3. Edit migrationSqlByTag ← automated by this script
 *   4. Edit migrationsBundle  ← automated by this script
 *
 * Usage:
 *   pnpm db:generate    # drizzle-kit generate + gen barrel
 *   npx tsx scripts/gen-migration-barrel.ts   # standalone
 */

import { readFileSync, writeFileSync, readdirSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const MIGRATIONS_DIR = resolve(__dirname, '../drizzle/migrations');
const JOURNAL_PATH = resolve(MIGRATIONS_DIR, 'meta/_journal.json');
const OUTPUT_PATH = resolve(MIGRATIONS_DIR, 'index.ts');

interface JournalEntry {
  readonly idx: number;
  readonly version: string;
  readonly when: number;
  readonly tag: string;
  readonly breakpoints: boolean;
}

interface Journal {
  readonly version: string;
  readonly dialect: string;
  readonly entries: readonly JournalEntry[];
}

function readJournal(): Journal {
  const raw = readFileSync(JOURNAL_PATH, 'utf-8');
  return JSON.parse(raw) as Journal;
}

function findMigrationFiles(): Set<string> {
  const files = readdirSync(MIGRATIONS_DIR);
  const migrationFiles = new Set<string>();
  for (const f of files) {
    // Match pattern: 0000_name.ts (but not index.ts)
    if (/^\d{4}_.*\.ts$/.test(f) && f !== 'index.ts') {
      migrationFiles.add(f.replace('.ts', ''));
    }
  }
  return migrationFiles;
}

type Entries = readonly JournalEntry[];

function header(count: number): readonly string[] {
  return [
    '/**',
    ' * Migrations bundle for `@xangarro/data`.',
    ' *',
    ' * ⚠️  AUTO-GENERATED by `scripts/gen-migration-barrel.ts`.',
    ' * Do not edit manually. Run `pnpm db:generate` to regenerate.',
    ' *',
    ` * ${count} migration(s) registered.`,
    ' */',
    '',
    "import journal from './meta/_journal.json';",
  ];
}

function importLines(entries: Entries): readonly string[] {
  return entries.map(
    (e) => `import { ${tagToVarName(e.tag)} } from './${tagToFileName(e.tag)}.js';`,
  );
}

function sqlByTagLines(entries: Entries): readonly string[] {
  return [
    'export const migrationSqlByTag: Readonly<Record<string, string>> = Object.freeze({',
    ...entries.map((e) => `  '${e.tag}': ${tagToVarName(e.tag)},`),
    '});',
    '',
  ];
}

function bundleLines(entries: Entries): readonly string[] {
  return [
    'export const migrationsBundle = Object.freeze({',
    '  journal,',
    '  migrations: Object.freeze({',
    ...entries.map((e) => `    m${String(e.idx).padStart(4, '0')}: ${tagToVarName(e.tag)},`),
    '  }),',
    '});',
    '',
  ];
}

function namedExportLines(entries: Entries): readonly string[] {
  return [
    'export {',
    '  journal,',
    ...entries.map((e) => `  ${tagToVarName(e.tag)},`),
    '};',
    'export default migrationsBundle;',
    '',
  ];
}

function generateBarrel(journal: Journal): string {
  const entries = journal.entries;
  return [
    ...header(entries.length),
    ...importLines(entries),
    '',
    ...sqlByTagLines(entries),
    ...bundleLines(entries),
    ...namedExportLines(entries),
  ].join('\n');
}

/** Convert a tag like '0000_initial' to variable name 'migration0000Sql'. */
function tagToVarName(tag: string): string {
  const idx = tag.slice(0, 4);
  return `migration${idx}Sql`;
}

/** Convert a tag like '0000_initial' to filename '0000_initial'. */
function tagToFileName(tag: string): string {
  return tag;
}

// Main
const journal = readJournal();
const filesOnDisk = findMigrationFiles();

// Validate: every journal tag must have a .ts file
const missing: string[] = [];
for (const entry of journal.entries) {
  if (!filesOnDisk.has(entry.tag)) {
    missing.push(entry.tag);
  }
}
if (missing.length > 0) {
  console.error(`❌ Journal references migration(s) without .ts files: ${missing.join(', ')}`);
  process.exit(1);
}

const barrel = generateBarrel(journal);
writeFileSync(OUTPUT_PATH, barrel, 'utf-8');
console.log(`✅ Generated ${OUTPUT_PATH} with ${journal.entries.length} migration(s)`);
