/**
 * Fullstack scenario 8 — Informe mensual reconciliation.
 *
 * Business narrative:
 *   1. Seed known ventas + egresos for April 2026
 *   2. Generate InformeMensual
 *   3. Verify totals reconcile: ventasPorCategoria, egresosPorCategoria,
 *      EstadoDeResultados (ingresos - egresos - ISR)
 *   4. Invalid yearMonth format → rejected
 *
 * Covers: RPT-01, RPT-03, RPT-04
 */

import { beforeEach, describe, expect, it } from 'vitest';
import type { BusinessId, ProductId, UserId } from '@cachink/domain';
import { newEntityId, type IsoDate } from '@cachink/domain';
import {
  makeNewBusiness,
  makeNewProduct,
  makeNewSale,
  makeNewExpense,
} from '../../../testing/src/index.js';
import { buildHarness, type FullstackHarness } from './fullstack-harness.js';

const USER_ID = newEntityId<UserId>();

describe('Informe Mensual — Reconciliation [fullstack]', () => {
  let h: FullstackHarness;
  let productId: ProductId;
  /** The real business ID generated by Drizzle (not the fixture constant). */
  let bizId: BusinessId;

  beforeEach(async () => {
    h = buildHarness({ userId: USER_ID, stockEnabled: false });

    // Business with 3% ISR (300 basis points)
    const biz = await h.repos.businesses.create(
      makeNewBusiness({ isrTasa: 300 }),
    );
    bizId = biz.id;

    const product = await h.repos.products.create(
      makeNewProduct({ businessId: bizId, seguirStock: false }),
    );
    productId = product.id;

    // Open caja for sales
    await h.useCases.abrirCaja.execute({
      userId: USER_ID,
      fecha: '2026-04-01' as IsoDate,
      montoAperturaCentavos: 500_00n,
      efectivoAdicionalCentavos: 0n,
      businessId: bizId,
    });

    // Seed 3 ventas in April 2026
    await h.useCases.registrarVenta.execute(
      makeNewSale({
        businessId: bizId,
        productoId: productId,
        fecha: '2026-04-05' as IsoDate,
        monto: 10_000n,
        categoria: 'Producto',
      }),
    );
    await h.useCases.registrarVenta.execute(
      makeNewSale({
        businessId: bizId,
        productoId: productId,
        fecha: '2026-04-15' as IsoDate,
        monto: 20_000n,
        categoria: 'Servicio',
      }),
    );
    await h.useCases.registrarVenta.execute(
      makeNewSale({
        businessId: bizId,
        productoId: productId,
        fecha: '2026-04-25' as IsoDate,
        monto: 15_000n,
        categoria: 'Producto',
      }),
    );

    // Seed 2 egresos
    await h.repos.expenses.create(
      makeNewExpense({
        businessId: bizId,
        fecha: '2026-04-10' as IsoDate,
        monto: 8_000n,
        categoria: 'Renta',
      }),
    );
    await h.repos.expenses.create(
      makeNewExpense({
        businessId: bizId,
        fecha: '2026-04-20' as IsoDate,
        monto: 5_000n,
        categoria: 'Nómina',
      }),
    );
  });

  it('generates informe with correct totals', async () => {
    const informe = await h.useCases.generarInforme.execute({
      businessId: bizId,
      yearMonth: '2026-04',
    });

    expect(informe.yearMonth).toBe('2026-04');

    // Verify ventas count
    expect(informe.ventas.length).toBe(3);

    // Verify egresos count
    expect(informe.egresos.length).toBe(2);

    // Verify ventas por categoría
    expect(informe.ventasPorCategoria['Producto']).toBe(25_000n); // 10000 + 15000
    expect(informe.ventasPorCategoria['Servicio']).toBe(20_000n);

    // Verify egresos por categoría
    expect(informe.egresosPorCategoria['Renta']).toBe(8_000n);
    expect(informe.egresosPorCategoria['Nómina']).toBe(5_000n);

    // Verify Estado de Resultados
    const edr = informe.estadoResultados;
    // Ingresos: 10000 + 20000 + 15000 = 45000
    expect(edr.ingresos).toBe(45_000n);
    // gastosOperativos: Renta(8000) + Nómina(5000) = 13000 (neither is Inventario/MateriaPrima)
    expect(edr.gastosOperativos).toBe(13_000n);
    // Utilidad bruta: 45000 - 0 (no costo de ventas) = 45000
    expect(edr.utilidadBruta).toBe(45_000n);
  });

  it('rejects invalid yearMonth format', async () => {
    await expect(
      h.useCases.generarInforme.execute({
        businessId: bizId,
        yearMonth: '2026/04',
      }),
    ).rejects.toThrow(/YYYY-MM/i);
  });

  it('returns empty arrays for a month with no data', async () => {
    const informe = await h.useCases.generarInforme.execute({
      businessId: bizId,
      yearMonth: '2026-01', // January — no seeded data
    });

    expect(informe.ventas.length).toBe(0);
    expect(informe.egresos.length).toBe(0);
    expect(informe.estadoResultados.ingresos).toBe(0n);
  });
});
