/**
 * What counts as one transaction (OQ-5, closed 2026-09-17): one per venta
 * ticket (not per line), one per gasto, one per manual inventory movement.
 * Cancellations, corte de día, caja movements and turnos, abonos, operator
 * messages and stock changes generated by a sale are not counted.
 *
 * Cancelling or soft-deleting a counted row does not un-count it: the push
 * counter increments on insert, and the nightly recompute must agree with it.
 */

import type { MovementOrigin, UsageRecord } from './types.js';

export function countsTowardUsage(record: UsageRecord): boolean {
  switch (record.kind) {
    case 'ticket':
    case 'gasto':
      return true;
    case 'ventaLinea':
      return record.ticketId === null;
    case 'movimientoInventario':
      return record.origen === 'manual';
    default:
      return false;
  }
}

/** Prefix `CancelarVentaUseCase` writes on the stock it returns. */
const CANCELLATION_NOTE_PREFIX = 'Cancelación de venta:';

/**
 * Best-effort origin of a stored `InventoryMovement`, until the entity
 * carries an explicit origin column. Mirrors what the application use cases
 * write today: `RegistrarVenta` → motivo `Venta`; `CancelarVenta` → motivo
 * `Devolución de cliente` with a `Cancelación de venta:` note;
 * `EjecutarConversion` → motivo `Conversión`. Everything else was entered by
 * a person.
 */
export function classifyMovementOrigin(movement: {
  readonly motivo: string;
  readonly nota?: string | null;
}): MovementOrigin {
  if (movement.motivo === 'Venta') return 'venta';
  if (movement.motivo === 'Conversión') return 'conversion';
  const nota = movement.nota ?? '';
  if (movement.motivo === 'Devolución de cliente' && nota.startsWith(CANCELLATION_NOTE_PREFIX)) {
    return 'cancelacion';
  }
  return 'manual';
}
