'use client';

import type { ProductIcon } from '@xangarro/domain';
import {
  Beef,
  Apple,
  Cake,
  Candy,
  Cookie,
  Croissant,
  Drumstick,
  Egg,
  Fish,
  IceCreamCone,
  Leaf,
  Nut,
  Pizza,
  Popcorn,
  Salad,
  Sandwich,
  Soup,
  Beer,
  Coffee,
  CupSoda,
  GlassWater,
  Grape,
  Martini,
  Milk,
  Wine,
  Gift,
  Gem,
  Shirt,
  SportShoe,
  ShoppingBag,
  Store,
  Tag,
  Watch,
  Car,
  Hammer,
  HardHat,
  Paintbrush,
  Plug,
  Scissors,
  SprayCan,
  Stethoscope,
  Wrench,
  Bath,
  Sparkles,
  Sun,
  Droplets,
  Heart,
  Armchair,
  Book,
  Briefcase,
  Lamp,
  PenTool,
  Printer,
  Archive,
  Box,
  ClipboardList,
  Flower2,
  Music,
  Package,
  Palette,
  PawPrint,
  Pill,
  Star,
  Ticket,
  Trophy,
  Zap,
  type LucideIcon,
} from 'lucide-react';

/**
 * The product icons as Lucide glyphs (P-07). Only these 66 are imported, not
 * the whole set, and the map is checked against `ProductIcon`: an icon added
 * to the domain without a glyph here does not compile.
 */
const GLYPHS = {
  beef: Beef,
  apple: Apple,
  cake: Cake,
  candy: Candy,
  cookie: Cookie,
  croissant: Croissant,
  drumstick: Drumstick,
  egg: Egg,
  fish: Fish,
  'ice-cream-cone': IceCreamCone,
  leaf: Leaf,
  nut: Nut,
  pizza: Pizza,
  popcorn: Popcorn,
  salad: Salad,
  sandwich: Sandwich,
  soup: Soup,
  beer: Beer,
  coffee: Coffee,
  'cup-soda': CupSoda,
  'glass-water': GlassWater,
  grape: Grape,
  martini: Martini,
  milk: Milk,
  wine: Wine,
  gift: Gift,
  gem: Gem,
  shirt: Shirt,
  'sport-shoe': SportShoe,
  'shopping-bag': ShoppingBag,
  store: Store,
  tag: Tag,
  watch: Watch,
  car: Car,
  hammer: Hammer,
  'hard-hat': HardHat,
  paintbrush: Paintbrush,
  plug: Plug,
  scissors: Scissors,
  'spray-can': SprayCan,
  stethoscope: Stethoscope,
  wrench: Wrench,
  bath: Bath,
  sparkles: Sparkles,
  sun: Sun,
  droplets: Droplets,
  heart: Heart,
  armchair: Armchair,
  book: Book,
  briefcase: Briefcase,
  lamp: Lamp,
  'pen-tool': PenTool,
  printer: Printer,
  archive: Archive,
  box: Box,
  'clipboard-list': ClipboardList,
  'flower-2': Flower2,
  music: Music,
  package: Package,
  palette: Palette,
  'paw-print': PawPrint,
  pill: Pill,
  star: Star,
  ticket: Ticket,
  trophy: Trophy,
  zap: Zap,
} as const satisfies Record<ProductIcon, LucideIcon>;

export function ProductGlyph({
  icon,
  size = 22,
}: {
  readonly icon: ProductIcon;
  readonly size?: number;
}) {
  const Glyph = GLYPHS[icon];
  return <Glyph size={size} strokeWidth={2.2} aria-hidden="true" />;
}
