/**
 * Native icon map — product-category icons (food, drink, services, etc.).
 *
 * Split from icon-map.native.ts to keep files under 200 lines.
 * Core UI icons live in icon-map-core.native.ts.
 */
import {
  Apple,
  Armchair,
  Bath,
  Beef,
  Beer,
  Book,
  Box,
  Briefcase,
  Candy,
  Car,
  Coffee,
  Cookie,
  Croissant,
  CupSoda,
  Droplets,
  Drumstick,
  Egg,
  Fish,
  Flower2,
  Gem,
  Gift,
  GlassWater,
  Grape,
  Hammer,
  HardHat,
  Heart,
  IceCreamCone,
  Lamp,
  Leaf,
  Martini,
  Milk,
  Music,
  Nut,
  Paintbrush,
  Palette,
  PawPrint,
  PenTool,
  Pill,
  Pizza,
  Popcorn,
  Printer,
  Salad,
  Sandwich,
  Scissors,
  Shirt,
  Soup,
  Sparkles,
  SprayCan,
  SportShoe,
  Star,
  Stethoscope,
  Store,
  Sun,
  Ticket,
  Trophy,
  Watch,
  Wine,
  Wrench,
} from 'lucide-react-native';
import type { Home } from 'lucide-react-native';
import type { IconName } from './icon.shared';

/** Product-category icons — merged with core icons in icon-map.native.ts. */
export const ICONS_PRODUCT: Partial<Record<IconName, typeof Home>> = {
  beef: Beef,
  apple: Apple,
  candy: Candy,
  cookie: Cookie,
  croissant: Croissant,
  drumstick: Drumstick,
  egg: Egg,
  fish: Fish,
  'ice-cream-cone': IceCreamCone,
  leaf: Leaf,
  nut: Nut,
  pizza: Pizza,
  popcorn: Popcorn,
  salad: Salad,
  sandwich: Sandwich,
  soup: Soup,
  beer: Beer,
  coffee: Coffee,
  'cup-soda': CupSoda,
  'glass-water': GlassWater,
  grape: Grape,
  martini: Martini,
  milk: Milk,
  wine: Wine,
  gift: Gift,
  gem: Gem,
  shirt: Shirt,
  'sport-shoe': SportShoe,
  store: Store,
  watch: Watch,
  car: Car,
  hammer: Hammer,
  'hard-hat': HardHat,
  paintbrush: Paintbrush,
  scissors: Scissors,
  'spray-can': SprayCan,
  stethoscope: Stethoscope,
  wrench: Wrench,
  bath: Bath,
  sparkles: Sparkles,
  sun: Sun,
  droplets: Droplets,
  heart: Heart,
  armchair: Armchair,
  book: Book,
  briefcase: Briefcase,
  lamp: Lamp,
  'pen-tool': PenTool,
  printer: Printer,
  box: Box,
  'flower-2': Flower2,
  music: Music,
  palette: Palette,
  'paw-print': PawPrint,
  pill: Pill,
  star: Star,
  ticket: Ticket,
  trophy: Trophy,
};
