/**
 * Native icon map — maps IconName to lucide-react-native components.
 *
 * Extracted from icon.native.tsx to keep files under 200 lines.
 */
import {
  Apple, Archive, Armchair, ArrowDownUp, Banknote, Bath, Beef, Beer,
  Bell, Book, Box, Briefcase, Building2, Cake, Calendar, Camera, Candy,
  Car, ChartBar, Check, ChevronDown, ChevronLeft, ChevronRight, ChevronUp,
  CircleAlert, CircleHelp, CircleX, ClipboardList, Cloud, Coffee, Coins,
  Cookie, CreditCard, Croissant, CupSoda, DollarSign, Droplets, Drumstick,
  Egg, Ellipsis, Eye, EyeOff, FileText, Fish, Flower2, Gem, Gift,
  GlassWater, Grape, Hammer, HandCoins, HardDrive, HardHat, Heart, Home,
  IceCreamCone, Inbox, Info, Lamp, Landmark, LayoutDashboard, LayoutGrid,
  Leaf, Lock, Martini, Milk, Minus, Monitor, Music, Nut, Package,
  Paintbrush, Palette, PawPrint, Pencil, PenTool, Pill, Pizza, Plug, Plus,
  Popcorn, Printer, Receipt, RefreshCw, Salad, Sandwich, ScanBarcode,
  Scissors, Search, Settings, Share2, Shirt, SportShoe, ShoppingBag,
  ShoppingCart, Sliders, Smartphone, Soup, Sparkles, SprayCan, Star,
  Stethoscope, Store, Sun, Tag, Ticket, Trash2, TrendingDown, TrendingUp,
  TriangleAlert, Trophy, Truck, User, UserCheck, Users, Utensils, Wallet,
  Watch, Wine, Wrench, X, Zap,
} from 'lucide-react-native';
import type { IconName } from './icon.shared';

export const ICONS: Record<IconName, typeof Home> = {
  home: Home,
  'layout-dashboard': LayoutDashboard,
  'layout-grid': LayoutGrid,
  settings: Settings,
  ellipsis: Ellipsis,
  'dollar-sign': DollarSign,
  banknote: Banknote,
  wallet: Wallet,
  coins: Coins,
  'hand-coins': HandCoins,
  'credit-card': CreditCard,
  receipt: Receipt,
  archive: Archive,
  package: Package,
  'scan-barcode': ScanBarcode,
  'shopping-bag': ShoppingBag,
  'shopping-cart': ShoppingCart,
  'chart-bar': ChartBar,
  'trending-up': TrendingUp,
  'trending-down': TrendingDown,
  plus: Plus,
  minus: Minus,
  x: X,
  check: Check,
  'share-2': Share2,
  pencil: Pencil,
  'trash-2': Trash2,
  users: Users,
  user: User,
  'user-check': UserCheck,
  bell: Bell,
  'circle-alert': CircleAlert,
  'circle-help': CircleHelp,
  info: Info,
  'file-text': FileText,
  eye: Eye,
  'eye-off': EyeOff,
  camera: Camera,
  calendar: Calendar,
  search: Search,
  smartphone: Smartphone,
  'building-2': Building2,
  cake: Cake,
  truck: Truck,
  utensils: Utensils,
  'clipboard-list': ClipboardList,
  'hard-drive': HardDrive,
  cloud: Cloud,
  plug: Plug,
  monitor: Monitor,
  inbox: Inbox,
  'refresh-cw': RefreshCw,
  zap: Zap,
  sliders: Sliders,
  'chevron-up': ChevronUp,
  'chevron-down': ChevronDown,
  'chevron-left': ChevronLeft,
  'chevron-right': ChevronRight,
  landmark: Landmark,
  'arrow-down-up': ArrowDownUp,
  'circle-x': CircleX,
  lock: Lock,
  'triangle-alert': TriangleAlert,
  beef: Beef,
  apple: Apple,
  candy: Candy,
  cookie: Cookie,
  croissant: Croissant,
  drumstick: Drumstick,
  egg: Egg,
  fish: Fish,
  'ice-cream-cone': IceCreamCone,
  leaf: Leaf,
  nut: Nut,
  pizza: Pizza,
  popcorn: Popcorn,
  salad: Salad,
  sandwich: Sandwich,
  soup: Soup,
  beer: Beer,
  coffee: Coffee,
  'cup-soda': CupSoda,
  'glass-water': GlassWater,
  grape: Grape,
  martini: Martini,
  milk: Milk,
  wine: Wine,
  gift: Gift,
  gem: Gem,
  shirt: Shirt,
  'sport-shoe': SportShoe,
  store: Store,
  tag: Tag,
  watch: Watch,
  car: Car,
  hammer: Hammer,
  'hard-hat': HardHat,
  paintbrush: Paintbrush,
  scissors: Scissors,
  'spray-can': SprayCan,
  stethoscope: Stethoscope,
  wrench: Wrench,
  bath: Bath,
  sparkles: Sparkles,
  sun: Sun,
  droplets: Droplets,
  heart: Heart,
  armchair: Armchair,
  book: Book,
  briefcase: Briefcase,
  lamp: Lamp,
  'pen-tool': PenTool,
  printer: Printer,
  box: Box,
  'flower-2': Flower2,
  music: Music,
  palette: Palette,
  'paw-print': PawPrint,
  pill: Pill,
  star: Star,
  ticket: Ticket,
  trophy: Trophy,
};
