/**
 * Native icon map — core UI icons (navigation, money, actions, status).
 *
 * Split from icon-map.native.ts to keep files under 200 lines.
 * Product-category icons live in icon-map-product.native.ts.
 */
import {
  Archive,
  ArrowDownUp,
  Banknote,
  Bell,
  Building2,
  Cake,
  Calendar,
  Camera,
  ChartBar,
  Check,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  CircleAlert,
  CircleHelp,
  CircleX,
  ClipboardList,
  Cloud,
  Coins,
  CreditCard,
  DollarSign,
  Ellipsis,
  Eye,
  EyeOff,
  FileText,
  HandCoins,
  HardDrive,
  Home,
  Inbox,
  Info,
  Landmark,
  LayoutDashboard,
  LayoutGrid,
  Lock,
  Minus,
  Monitor,
  Package,
  Pencil,
  Plug,
  Plus,
  Receipt,
  RefreshCw,
  ScanBarcode,
  Search,
  Settings,
  Share2,
  ShoppingBag,
  ShoppingCart,
  Sliders,
  Smartphone,
  Tag,
  Trash2,
  TrendingDown,
  TrendingUp,
  TriangleAlert,
  Truck,
  User,
  UserCheck,
  Users,
  Utensils,
  Wallet,
  X,
  Zap,
} from 'lucide-react-native';
import type { IconName } from './icon.shared';

/** Core UI icons — merged with product icons in icon-map.native.ts. */
export const ICONS_CORE: Partial<Record<IconName, typeof Home>> = {
  home: Home,
  'layout-dashboard': LayoutDashboard,
  'layout-grid': LayoutGrid,
  settings: Settings,
  ellipsis: Ellipsis,
  'dollar-sign': DollarSign,
  banknote: Banknote,
  wallet: Wallet,
  coins: Coins,
  'hand-coins': HandCoins,
  'credit-card': CreditCard,
  receipt: Receipt,
  archive: Archive,
  package: Package,
  'scan-barcode': ScanBarcode,
  'shopping-bag': ShoppingBag,
  'shopping-cart': ShoppingCart,
  'chart-bar': ChartBar,
  'trending-up': TrendingUp,
  'trending-down': TrendingDown,
  plus: Plus,
  minus: Minus,
  x: X,
  check: Check,
  'share-2': Share2,
  pencil: Pencil,
  'trash-2': Trash2,
  users: Users,
  user: User,
  'user-check': UserCheck,
  bell: Bell,
  'circle-alert': CircleAlert,
  'circle-help': CircleHelp,
  info: Info,
  'file-text': FileText,
  eye: Eye,
  'eye-off': EyeOff,
  camera: Camera,
  calendar: Calendar,
  search: Search,
  smartphone: Smartphone,
  'building-2': Building2,
  cake: Cake,
  truck: Truck,
  utensils: Utensils,
  'clipboard-list': ClipboardList,
  'hard-drive': HardDrive,
  cloud: Cloud,
  plug: Plug,
  monitor: Monitor,
  inbox: Inbox,
  'refresh-cw': RefreshCw,
  zap: Zap,
  sliders: Sliders,
  'chevron-up': ChevronUp,
  'chevron-down': ChevronDown,
  'chevron-left': ChevronLeft,
  'chevron-right': ChevronRight,
  landmark: Landmark,
  'arrow-down-up': ArrowDownUp,
  'circle-x': CircleX,
  lock: Lock,
  'triangle-alert': TriangleAlert,
  tag: Tag,
};
