import type { CajaData } from './types';

/**
 * The design's catalogue, clients and seeded ticket (`Operador Caja.dc.html`),
 * in centavos. The design marks a product low at 10 or fewer. Replaced in O-06.
 */
export const CAJA_FIXTURE: CajaData = {
  negocio: 'Taquería Don Pedro',
  caja: 'Caja 1',
  ventasTurno: 12,
  siguienteFolio: 'V-0413',
  catalogo: [
    {
      id: 'taco-de-pastor',
      nombre: 'Taco de pastor',
      precio: 25_00n,
      categoria: 'Tacos',
      existencias: 140,
      umbral: 10,
      icono: 'flame',
    },
    {
      id: 'taco-de-suadero',
      nombre: 'Taco de suadero',
      precio: 27_00n,
      categoria: 'Tacos',
      existencias: 96,
      umbral: 10,
      icono: 'drumstick',
    },
    {
      id: 'taco-de-bistec',
      nombre: 'Taco de bistec',
      precio: 30_00n,
      categoria: 'Tacos',
      existencias: 74,
      umbral: 10,
      icono: 'ham',
    },
    {
      id: 'taco-de-chorizo',
      nombre: 'Taco de chorizo',
      precio: 25_00n,
      categoria: 'Tacos',
      existencias: 58,
      umbral: 10,
      icono: 'drumstick',
    },
    {
      id: 'taco-campechano',
      nombre: 'Taco campechano',
      precio: 30_00n,
      categoria: 'Tacos',
      existencias: 41,
      umbral: 10,
      icono: 'utensils',
    },
    {
      id: 'taco-de-tripa',
      nombre: 'Taco de tripa',
      precio: 32_00n,
      categoria: 'Tacos',
      existencias: 6,
      umbral: 10,
      icono: 'utensils',
    },
    {
      id: 'gringa',
      nombre: 'Gringa',
      precio: 60_00n,
      categoria: 'Guisados',
      existencias: 33,
      umbral: 10,
      icono: 'pizza',
    },
    {
      id: 'quesadilla',
      nombre: 'Quesadilla',
      precio: 45_00n,
      categoria: 'Guisados',
      existencias: 48,
      umbral: 10,
      icono: 'pizza',
    },
    {
      id: 'volcan',
      nombre: 'Volcán',
      precio: 55_00n,
      categoria: 'Guisados',
      existencias: 27,
      umbral: 10,
      icono: 'flame',
    },
    {
      id: 'orden-de-pastor',
      nombre: 'Orden de pastor',
      precio: 120_00n,
      categoria: 'Guisados',
      existencias: 19,
      umbral: 10,
      icono: 'pot',
    },
    {
      id: 'agua-de-horchata',
      nombre: 'Agua de horchata',
      precio: 25_00n,
      categoria: 'Bebidas',
      existencias: 22,
      umbral: 10,
      icono: 'glass',
    },
    {
      id: 'agua-de-jamaica',
      nombre: 'Agua de jamaica',
      precio: 25_00n,
      categoria: 'Bebidas',
      existencias: 18,
      umbral: 10,
      icono: 'glass',
    },
    {
      id: 'refresco-600-ml',
      nombre: 'Refresco 600 ml',
      precio: 28_00n,
      categoria: 'Bebidas',
      existencias: 64,
      umbral: 10,
      icono: 'soda',
    },
    {
      id: 'agua-embotellada',
      nombre: 'Agua embotellada',
      precio: 15_00n,
      categoria: 'Bebidas',
      existencias: 3,
      umbral: 10,
      icono: 'bottle',
    },
    {
      id: 'consome',
      nombre: 'Consomé',
      precio: 35_00n,
      categoria: 'Extras',
      existencias: 25,
      umbral: 10,
      icono: 'soup',
    },
    {
      id: 'cebollitas-asadas',
      nombre: 'Cebollitas asadas',
      precio: 20_00n,
      categoria: 'Extras',
      existencias: 30,
      umbral: 10,
      icono: 'leafy',
    },
    {
      id: 'guacamole',
      nombre: 'Guacamole',
      precio: 25_00n,
      categoria: 'Extras',
      existencias: 12,
      umbral: 10,
      icono: 'salad',
    },
    {
      id: 'salsa-extra',
      nombre: 'Salsa extra',
      precio: 8_00n,
      categoria: 'Extras',
      existencias: 80,
      umbral: 10,
      icono: 'droplet',
    },
  ],
  clientes: [
    { id: 'mari', nombre: 'Doña Mari de la tienda', telefono: '5512 447 903', saldo: 340_00n },
    { id: 'chuy', nombre: 'Taller de Chuy', telefono: '5533 981 204', saldo: 1260_00n },
    { id: 'delgado', nombre: 'Oficina Delgado', telefono: '5544 120 887', saldo: 0n },
    { id: 'raul', nombre: 'Raúl (obra de la esquina)', telefono: '5521 664 019', saldo: 580_00n },
  ],
  ticket: [
    { productoId: 'taco-de-pastor', nombre: 'Taco de pastor', precio: 25_00n, cantidad: 3 },
    { productoId: 'gringa', nombre: 'Gringa', precio: 60_00n, cantidad: 1 },
    { productoId: 'agua-de-horchata', nombre: 'Agua de horchata', precio: 25_00n, cantidad: 1 },
  ],
};
