import assert from 'node:assert/strict';
import { describe, it } from 'vitest';
import {
  APERTURA_MOTIVO,
  classifyMovementOrigin,
  countsTowardUsage,
  PORTAL_DEVICE_ID,
  type UsageRecord,
} from '../../src/usage/index.js';

const AT = '2026-09-10T18:00:00.000Z';

describe('countsTowardUsage (OQ-5)', () => {
  it('counts one per venta ticket, one per gasto and one per manual movement', () => {
    const counted: UsageRecord[] = [
      { kind: 'ticket', at: AT },
      { kind: 'gasto', at: AT },
      { kind: 'movimientoInventario', at: AT, origen: 'manual' },
      { kind: 'movimientoInventario', at: AT, origen: 'portal' },
    ];
    for (const r of counted) assert.equal(countsTowardUsage(r), true, r.kind);
  });

  it('does not count sale lines that belong to a ticket', () => {
    assert.equal(countsTowardUsage({ kind: 'ventaLinea', at: AT, ticketId: 'T1' }), false);
  });

  it('counts a legacy sale with no ticket as its own one-line ticket', () => {
    assert.equal(countsTowardUsage({ kind: 'ventaLinea', at: AT, ticketId: null }), true);
  });

  it('does not count stock changes generated by a sale, a cancellation or a conversion', () => {
    for (const origen of ['venta', 'cancelacion', 'conversion'] as const) {
      assert.equal(countsTowardUsage({ kind: 'movimientoInventario', at: AT, origen }), false);
    }
  });

  it('does not count cancellations, corte, caja, abonos, messages or products', () => {
    const kinds = [
      'cancelacion',
      'corteDeDia',
      'cajaMovimiento',
      'cajaTurno',
      'abono',
      'mensajeOperador',
    ] as const;
    for (const kind of kinds) assert.equal(countsTowardUsage({ kind, at: AT }), false, kind);
    assert.equal(countsTowardUsage({ kind: 'producto', deletedAt: null }), false);
  });
});

describe('classifyMovementOrigin', () => {
  it('classifies a user-entered entrada, ajuste or merma as manual', () => {
    assert.equal(classifyMovementOrigin({ motivo: 'Compra a proveedor', nota: null }), 'manual');
    // N-17: opening stock is apertura wherever it was written, and never counts.
    assert.equal(classifyMovementOrigin({ motivo: APERTURA_MOTIVO }), 'apertura');
    assert.equal(classifyMovementOrigin({ motivo: APERTURA_MOTIVO, deviceId: 'dev' }), 'apertura');
    assert.equal(
      countsTowardUsage({
        kind: 'movimientoInventario',
        at: '2026-09-18T12:00:00Z',
        origen: 'apertura',
      }),
      false,
    );
    assert.equal(classifyMovementOrigin({ motivo: 'Ajuste de inventario', nota: 'x' }), 'manual');
    assert.equal(classifyMovementOrigin({ motivo: 'Merma / daño', nota: null }), 'manual');
  });

  it('classifies the salida written by a venta as sale-generated', () => {
    assert.equal(classifyMovementOrigin({ motivo: 'Venta', nota: null }), 'venta');
  });

  it('classifies the entrada written by cancelling a venta as a cancellation', () => {
    const nota = 'Cancelación de venta: cliente se arrepintió';
    assert.equal(classifyMovementOrigin({ motivo: 'Devolución de cliente', nota }), 'cancelacion');
  });

  it('keeps a hand-entered customer return as manual', () => {
    const r = classifyMovementOrigin({ motivo: 'Devolución de cliente', nota: 'regresó 2' });
    assert.equal(r, 'manual');
  });

  it('classifies conversion movements as generated', () => {
    assert.equal(classifyMovementOrigin({ motivo: 'Conversión', nota: undefined }), 'conversion');
  });

  it('classifies a movement written in the portal as portal, whatever its motivo (C-12)', () => {
    const portal = { deviceId: PORTAL_DEVICE_ID };
    assert.equal(classifyMovementOrigin({ ...portal, motivo: 'Ajuste de inventario' }), 'portal');
    assert.equal(classifyMovementOrigin({ ...portal, motivo: 'Venta' }), 'portal');
  });

  it('applies the motivo heuristic to device rows only', () => {
    const phone = { deviceId: '01HZ8XQN9GZJXV8AKQ5X0PH0NE' };
    assert.equal(classifyMovementOrigin({ ...phone, motivo: 'Venta' }), 'venta');
    assert.equal(classifyMovementOrigin({ ...phone, motivo: 'Merma' }), 'manual');
  });
});
