/**
 * Visual regression snapshots for `@cachink/ui` stories.
 *
 * Storybook exposes each story at `/iframe.html?id=<kebab-title>--<kebab-story>`.
 * Playwright navigates to each URL, waits for the story to mount, and diffs
 * the rendered page against the committed baseline in `__snapshots__/`.
 *
 * To update baselines after an intentional visual change:
 *   pnpm --filter @cachink/ui test:visual --update-snapshots
 */
import { test, expect } from '@playwright/test';

const stories = [
  'phase-0-hellobadge--default',
  'phase-0-hellobadge--custom-text',
  'phase-1a-primitives-btn--primary',
  'phase-1a-primitives-btn--all-variants',
  'phase-1a-primitives-btn--pressed',
  'phase-1a-primitives-btn--disabled',
  'phase-1a-primitives-input--text',
  'phase-1a-primitives-input--number',
  'phase-1a-primitives-input--date',
  'phase-1a-primitives-input--select',
  'phase-1a-primitives-input--with-label-and-note',
  'phase-1a-primitives-tag--soft',
  'phase-1a-primitives-tag--success',
  'phase-1a-primitives-tag--danger',
  'phase-1a-primitives-tag--info',
  'phase-1a-primitives-tag--all-variants',
  'phase-1a-primitives-modal--default',
  'phase-1a-primitives-modal--with-title',
  'phase-1a-primitives-modal--with-title-and-emoji',
  'phase-1a-primitives-modal--nueva-venta',
  'phase-1a-primitives-modal--without-header',
  'phase-1a-primitives-empty-state--ventas-vacio',
  'phase-1a-primitives-empty-state--egresos-vacio',
  'phase-1a-primitives-empty-state--inventario-vacio',
  'phase-1a-primitives-empty-state--sin-resultados',
  'phase-1a-primitives-empty-state--titulo-solo',
  'phase-1a-primitives-section-title--ventas-hoy',
  'phase-1a-primitives-section-title--actividad-reciente',
  'phase-1a-primitives-section-title--stock-bajo',
  'phase-1a-primitives-section-title--cuentas-por-cobrar',
  'phase-1a-primitives-section-title--productos',
  'phase-1a-primitives-card--white-default',
  'phase-1a-primitives-card--yellow-hero',
  'phase-1a-primitives-card--black-director',
  'phase-1a-primitives-card--tappable',
  'phase-1a-primitives-card--all-variants',
  'phase-1a-primitives-kpi--ventas-hoy',
  'phase-1a-primitives-kpi--utilidad-mes',
  'phase-1a-primitives-kpi--egresos-hoy',
  'phase-1a-primitives-kpi--stock-total',
  'phase-1a-primitives-kpi--all-tones',
  'phase-1a-primitives-gauge--margen-bruto',
  'phase-1a-primitives-gauge--liquidez',
  'phase-1a-primitives-gauge--rotacion-inventario',
  'phase-1a-primitives-gauge--alerta',
  'phase-1a-primitives-gauge--all-tones',
  'phase-1a-primitives-bottom-tab-bar--operativo',
  'phase-1a-primitives-bottom-tab-bar--director',
  'phase-1a-primitives-bottom-tab-bar--with-badges',
  'phase-1a-primitives-bottom-tab-bar--iconless-fallback',
  'phase-1a-primitives-bottom-tab-bar--mid-selection',
  'phase-1a-primitives-top-bar--default',
  'phase-1a-primitives-top-bar--with-subtitle',
  'phase-1a-primitives-top-bar--operativo-screen',
  'phase-1a-primitives-top-bar--director-home',
  'phase-1a-primitives-top-bar--back-button',
  // Slice 8 M3-C14 — new screen + card stories.
  'phase-1d-screens-lan-host--starting',
  'phase-1d-screens-lan-host--ready',
  'phase-1d-screens-lan-host--error-state',
  'phase-1d-screens-lan-join--paste-only',
  'phase-1d-screens-lan-join--with-scanner',
  'phase-1d-screens-lan-join--error-state',
  'phase-1d-director-home-conflictos-recientes--empty',
  'phase-1d-director-home-conflictos-recientes--one-conflict',
  'phase-1d-director-home-conflictos-recientes--five-conflicts',
  'phase-1e-screens-password-reset--default',
  'phase-1e-screens-password-reset--sending',
  'phase-1f-settings-feedback-action--default',
  'phase-1f-settings-feedback-action--with-role-and-consent',
  // Audit Round 2 G2 — Storybook coverage gap closed for the
  // remaining standalone primitives + the field family.
  'phase-1a-primitives-error-state--ventas-fetch-failed',
  'phase-1a-primitives-error-state--egresos-fetch-failed',
  'phase-1a-primitives-error-state--unrecoverable',
  'phase-1a-primitives-fab--default',
  'phase-1a-primitives-fab--disabled',
  'phase-1a-primitives-fab--stacked',
  'phase-1a-primitives-fab--pressed',
  'phase-1a-primitives-list--ventas',
  'phase-1a-primitives-list--with-header-footer',
  'phase-1a-primitives-list--empty',
  'phase-1a-primitives-search-bar--empty',
  'phase-1a-primitives-search-bar--with-query',
  'phase-1a-primitives-search-bar--no-label',
  'phase-1a-primitives-skeleton--single-row',
  'phase-1a-primitives-skeleton--three-rows',
  'phase-1a-primitives-skeleton--bars',
  'phase-1c-primitives-period-picker--mensual',
  'phase-1c-primitives-period-picker--anual',
  'phase-1c-primitives-period-picker--rango',
  'phase-1c-primitives-scanner--closed',
  'phase-1c-primitives-scanner--open-single',
  'phase-1c-primitives-scanner--open-continuous',
  // Field family — RhfTextField / RhfMoneyField / RhfDateField / etc.
  'phase-1a-fields-textfield--controlled',
  'phase-1a-fields-textfield--rhf-controlled',
  'phase-1a-fields-textfield--with-note',
  'phase-1a-fields-moneyfield--empty',
  'phase-1a-fields-moneyfield--pre-filled',
  'phase-1a-fields-moneyfield--rhf-controlled',
  'phase-1a-fields-moneyfield--with-error',
  'phase-1a-fields-datefield--empty',
  'phase-1a-fields-datefield--today',
  'phase-1a-fields-datefield--rhf-controlled',
  'phase-1a-fields-integerfield--unbounded',
  'phase-1a-fields-integerfield--bounded',
  'phase-1a-fields-integerfield--rhf-controlled',
  'phase-1a-fields-emailfield--empty',
  'phase-1a-fields-emailfield--pre-filled',
  'phase-1a-fields-emailfield--rhf-controlled',
  'phase-1a-fields-phonefield--empty',
  'phase-1a-fields-phonefield--pre-filled',
  'phase-1a-fields-phonefield--rhf-controlled',
  'phase-1a-fields-passwordfield--sign-in',
  'phase-1a-fields-passwordfield--sign-up',
  'phase-1a-fields-passwordfield--rhf-controlled',
];

for (const id of stories) {
  test(`snapshot: ${id}`, async ({ page }) => {
    await page.goto(`/iframe.html?id=${id}&viewMode=story`);
    await page.waitForSelector('#storybook-root > *');
    await expect(page).toHaveScreenshot(`${id}.png`, { fullPage: true });
  });
}
