/**
 * The prose halves of `DESIGN_CONTRACT.md` — the parts that are written, not
 * generated. Everything derived from `@xangarro/tokens` lives in `render.ts`.
 *
 * Source: the design plan §1 and §2b (task P-19, ADR-057), brought to El
 * Mostrador by ADR-109. The full rules live in `docs/design/el-mostrador.md`.
 */

export const CONDITIONS: readonly (readonly [string, string])[] = [
  [
    'Estructura',
    'Mismo orden y jerarquía de bloques: barra lateral, encabezado, contenido a 1760 px máximo, panel de control.',
  ],
  [
    'Medidas',
    'Tres bordes: `thin` 2 px negro en lo que se toca, `thick` 2.5 px en el héroe y los diálogos, `quiet` 2 px gray200 en los paneles. Radios de la escala 8/10/12/14/16/18/20/22 (paneles en 20), sombras duras 3/4/5 px sin difuminado.',
  ],
  [
    'Color',
    'Solo tokens del sistema. Ningún color nuevo, ningún degradado, ninguna transparencia salvo el velo de modal.',
  ],
  [
    'Tipografía',
    'Plus Jakarta Sans; títulos en 800 con tracking negativo, etiquetas en mayúsculas 700 con tracking positivo, cuerpo 600.',
  ],
  [
    'Copy',
    'Español de México, de tú, como lo dicen los tableros aprobados. Sin rayas largas en el texto visible (salvo «—» como vacío). Métodos de pago: Efectivo, Tarjeta, Transferencia, Fiado.',
  ],
  [
    'Interacción',
    'El sello al presionar (2 px + sombra a 1 px, 100 ms) en todo lo tocable; hover solo eleva en escritorio. Detalles y formularios en panel lateral; confirmaciones en diálogo centrado.',
  ],
  [
    'Estados',
    'Cada lista y cada reporte implementan cargando, vacío, error y con datos, más el recorte por rol. Nunca datos de ejemplo en una pantalla viva; nada dice «Pronto» ni «Próximamente».',
  ],
  [
    'Accesibilidad',
    'Foco visible amarillo, objetivos de 44 px mínimo, contraste de 4.5:1 mínimo, severidad siempre con icono además de color.',
  ],
];

export const PROHIBITIONS: readonly string[] = [
  'No component library that brings its own styling. Radix supplies behaviour only; every pixel is ours (ADR-057).',
  'No Tailwind, and no utility framework whose defaults are not the tokens below.',
  'No hex literal, `rgba()`, radius, border width or font size written inline in a component. `pnpm lint:design` fails on all five.',
  'No icons outside the Lucide idiom, drawn inline at stroke-width 2.2–2.4 with `currentColor`.',
  'No emoji in the interface, except a single glyph as the visual in an empty state.',
  'No gradients, no blur, no soft shadows, no glassmorphism, no dark theme.',
  'No `gray400` as text. It is a fill; the `*Text` tokens are the legible pairs, on panels. Text set on the `gray200` page is `gray600` or `ink`: `textMuted` is 3.96:1 there.',
  'No yellow-filled chip as a selection: a selected chip is black with yellow text; only tabs and segmented options fill yellow.',
  'No action as a bare text link or a raw URL. Every action is a button.',
  'No more than one hero per screen, and never a hero inside a hero.',
  'Money is integer centavos and is formatted only at the boundary, with `@xangarro/domain` (CLAUDE.md §2.8).',
];

export const HEADER: readonly string[] = [
  '# DESIGN_CONTRACT.md — Xangarro! portal',
  '',
  '> **Generated by `pnpm design:contract`. Do not edit by hand.**',
  '> The token tables below are read from `@xangarro/tokens`, so this contract cannot',
  '> drift from the code it governs. Prose sections come from the design plan §1 and §2b,',
  '> updated for El Mostrador (ADR-109); the full rules are in `docs/design/el-mostrador.md`.',
  '',
  '> **La regla que ordena todo.** El diseño no es inspiración: es la especificación. Los',
  '> tableros de El Mostrador aprobados por el dueño en el lienzo mandan; si el código y un',
  '> tablero aprobado no coinciden, el código está mal. Cualquier cambio visual se dibuja',
  '> primero en el lienzo y después se traduce a tokens, nunca al revés.',
  '',
];

export const MOTION: readonly string[] = [
  '## 6. Motion',
  '',
  'Four motions, nothing else (ADR-107, ADR-109):',
  '',
  '- **Press**: `translate(2px, 2px)` with the shadow to `1px 1px 0`, 100 ms, `cubic-bezier(0.2, 0.8, 0.2, 1)`.',
  '- **Panel slide**: a side panel enters from the right in 280 ms while its scrim fades in 160 ms.',
  '- **Dialog pop**: a centred dialog scales up from 0.94–0.96 in 160–220 ms.',
  '- **Don Cuentas idle**: his pose breathes, waves, nods or jumps; the loader (`DonCargando`) tosses a coin. Never a shimmer, never a spinner.',
  '- **Cards may lift on hover** on desktop, `translate(-1px, -1px)` to `6px 6px 0`, 120 ms.',
  '- All of it is wrapped in `@media (prefers-reduced-motion: reduce)`, where it stops.',
  '',
];

export const VERIFICATION: readonly string[] = [
  '## 7. Verification',
  '',
  '1. **Comparación lado a lado** — `pnpm design:compare <pantalla>`. A review, never a CI gate.',
  '2. **Auditoría de valores** — `pnpm lint:design`. A CI gate, ratcheting; the baseline may fall, never rise.',
  '3. **Recorrido de estados y rol** — Playwright over the six states × three roles, with `@axe-core/playwright`.',
  '',
];
