/**
 * The prose halves of `DESIGN_CONTRACT.md` — the parts that are written, not
 * generated. Everything derived from `@xangarro/tokens` lives in `render.ts`.
 *
 * Source: the design plan §1 and §2b (task P-19, ADR-057).
 */

export const CONDITIONS: readonly (readonly [string, string])[] = [
  [
    'Estructura',
    'Mismo orden y jerarquía de bloques: barra lateral, encabezado, contenido a 1760 px máximo, panel de control.',
  ],
  [
    'Medidas',
    'Bordes de 2 px (2.5 px en tarjetas héroe y barras fijas), radios de la escala 8/10/12/14/16/18/20/22, sombras duras 3/4/5 px sin difuminado.',
  ],
  [
    'Color',
    'Solo tokens del sistema. Ningún color nuevo, ningún degradado, ninguna transparencia salvo el velo de modal.',
  ],
  [
    'Tipografía',
    'Plus Jakarta Sans; títulos en 800 con tracking negativo, etiquetas en mayúsculas 700 con tracking positivo, cuerpo 600.',
  ],
  [
    'Copy',
    'Textos en español (es-MX) copiados literalmente del diseño, incluidos montos y nombres de ejemplo. No se reescriben.',
  ],
  [
    'Interacción',
    'El sello al presionar (2 px + sombra a 1 px, 100 ms) en todo lo tocable; hover solo eleva en escritorio.',
  ],
  [
    'Estados',
    'Cada lista y cada reporte implementan cargando, vacío, error y con datos, más el recorte por rol.',
  ],
  [
    'Accesibilidad',
    'Foco visible amarillo, objetivos de 44 px mínimo, severidad siempre con icono además de color.',
  ],
];

export const PROHIBITIONS: readonly string[] = [
  'No component library that brings its own styling. Radix supplies behaviour only; every pixel is ours (ADR-057).',
  'No Tailwind, and no utility framework whose defaults are not the tokens below.',
  'No hex literal, `rgba()`, radius, border width or font size written inline in a component. `pnpm lint:design` fails on all five.',
  'No icons outside the Lucide idiom, drawn inline at stroke-width 2.2–2.4 with `currentColor`.',
  'No emoji in the interface, except a single glyph as the visual in an empty state.',
  'No gradients, no blur, no soft shadows, no glassmorphism, no dark theme.',
  'No `gray400` as text. It is a fill; the `*Text` tokens are the legible pairs.',
  'Money is integer centavos and is formatted only at the boundary, with `@xangarro/domain` (CLAUDE.md §2.8).',
];

export const HEADER: readonly string[] = [
  '# DESIGN_CONTRACT.md — Xangarro! portal',
  '',
  '> **Generated by `pnpm design:contract`. Do not edit by hand.**',
  '> The token tables below are read from `@xangarro/tokens`, so this contract cannot',
  '> drift from the code it governs. Prose sections come from the design plan §1 and §2b.',
  '',
  '> **La regla que ordena todo.** El diseño no es inspiración: es la especificación. Si',
  '> el código y el diseño no coinciden, el código está mal. Cualquier cambio visual se',
  '> hace primero en el archivo de diseño y después en el código, nunca al revés.',
  '',
];

export const MOTION: readonly string[] = [
  '## 6. Motion',
  '',
  '- **Press is the only global motion**: `translate(2px, 2px)` with the shadow to `1px 1px 0`, 100 ms, `cubic-bezier(0.2, 0.8, 0.2, 1)`.',
  '- **Cards may lift on hover**, `translate(-1px, -1px)` to `6px 6px 0`, 120 ms. That is the one exception.',
  '- Loading is a **static grey block**. Never a shimmer, never a spinner.',
  '- All of it is wrapped in `@media (prefers-reduced-motion: reduce)`.',
  '',
];

export const VERIFICATION: readonly string[] = [
  '## 7. Verification',
  '',
  '1. **Comparación lado a lado** — `pnpm design:compare <pantalla>`. A review, never a CI gate.',
  '2. **Auditoría de valores** — `pnpm lint:design`. A CI gate, ratcheting; the baseline may fall, never rise.',
  '3. **Recorrido de estados y rol** — Playwright over the six states × three roles, with `@axe-core/playwright`.',
  '',
];
